name: mindmorph
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  go_router: ^13.2.4
  velocity_x: ^4.1.2
  lottie: ^3.1.0
  image_picker: ^1.0.8
  http: ^1.2.1
  path: ^1.9.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf

    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf

    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf
