---
dependencies:
  appinio_video_player: ^1.3.0
  better_player: ^0.0.84
  cupertino_icons: ^1.0.8
  easy_search_bar: ^2.5.0
  equatable: ^2.0.5
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_file_downloader: ^2.0.0
  flutter_inappwebview: ^6.0.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_pdfview: ^1.3.2
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  form_validator: ^2.1.1
  get: ^4.6.6
  go_router: ^14.2.7
  http: ^1.2.2
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  lottie: ^3.1.2
  meta: ^1.15.0
  path: ^1.9.0
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.3
  socket_io_client: ^2.0.3
  url_launcher: ^6.3.0
  velocity_x: ^4.2.1
  webview_flutter: ^4.9.0
description: A new Flutter project.
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=3.3.0 <4.0.0'
flutter:
  assets:
    - assets/images/
  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf
    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf
    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf
  uses-material-design: true
name: mindmorph
publish_to: none
version: 1.0.0+1