name: mindmorph
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  velocity_x: ^4.2.1
  lottie: ^3.1.2
  image_picker: ^1.1.2
  http: ^1.2.1
  path: ^1.9.0
  http_parser: ^4.0.2
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  file_picker: ^8.0.5
  flutter_keyboard_visibility: ^6.0.0
  appinio_video_player: ^1.3.0
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  percent_indicator: ^4.2.3
  meta: ^1.12.0
  form_validator: ^2.1.1
  better_player: ^0.0.84
  easy_search_bar: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf

    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf

    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf
